### ISSUE TITLE
Missing options.version being reported when assigning Centos Workflow

### ISSUE THREAD

**Issue by davlloyd** [emccode/machine#2]
Not sure if I have missed anything but I get the same error repeatable (through a number of environment rebuilds) of a 'TemplateRenderingError' error reporting due to a missing value of 'options.version'. I have stripped the reference out of the Templates and Profiles to see if it changed the behaviour but still same result. Noticed while doing that a seperation in what file content is shown int the UI and what is on the host. Removing the reference to a version in these areas made no difference anyway.

Result of the error is that the workflow never gets passed the first action.

![screen shot 2016-03-22 at 12 07 25 am](https://cloud.githubusercontent.com/assets/7078556/13920655/4660b8ce-efc8-11e5-8085-37e28ee435c3.png)

**Comment by davlloyd** [comment]
Just a small mistake in the installation instructions in step 11, the curl command for the workflow upload specified a POST command where the API requires a PUT. The upload of a SKU definition is a POST so that is good. Thanks!

current:
curl -H "Content-Type: application/json" -X POST --data @centos_workflow.json http://localhost:9090/api/1.1/workflows

fixed example:
curl -H "Content-Type: application/json" -X PUT --data @centos_workflow.json http://localhost:9090/api/1.1/workflows

**Comment by davlloyd** [comment]
changes pushed up to readme.md and to workflow file to address issues

**Comment by clintkitson** [comment]
Thanks @davlloyd. @kenny can you review? https://github.com/emccode/machine/pull/4

**Comment by clintkitson** [comment]
Also https://github.com/emccode/machine/pull/3

**Comment by kacole2** [comment]
yes i will... thanks @davlloyd. I remember `options.version` being needed somewhere along my testing
